### ISSUE TITLE
تمپلیت برای xui

### ISSUE THREAD

**Issue by ExPLoSiVe1988** [MatinDehghanian/MarzneshinTemplates#1]
سلام خسته نباشید
لطفا اگر مقدوره برای پنل‌های xui هم تمپلیت بدید ممنون میشم

خیلی پنل xui تنها مونده تو این مباحث

**Comment by MatinDehghanian** [comment]
سلام و ارادت
پنل x-ui متاسفانه api برای دریافت بعضی از اطلاعات نداره توی صفحه سابسکریبشن
و خب آقایان ثنایی و علیرضا هم ظاهرا علاقه ای به اینکه html قبول کنه 3x-ui ندارند.
بازم من سعی میکنم که اگه به هر حالتی امکانش بود اضافه کنم

**Comment by ExPLoSiVe1988** [comment]
ممنون میشم اگر این امکان رو اضافه کنید به تمپلیت‌هاتون
با توجه به اینکه پروژه اوپن سورسه، میتونید پروژه رو فورک کنید و این امکان رو خودتون اگر براتون مقدوره اضافه کنید
بازم ممنون

**Comment by happybigboy** [comment]
میتونید از ربات ویزویز استفاده کنید که خودش لینک ساب بهتون میده. 
اگر هم چیز متفاوت تری میخواد هزینه کنید براتون آماده می کنن

**Comment by ExPLoSiVe1988** [comment]
ویزویز دارم و خودم شخصی سازی هم کردم و استفاده هم میکنم
شخصی نبود ایشو بنده و به صورت کلی گفتم

اگر میشه برای کسانی که از پنل‌های xui استفاده میکنند تمپلیت اضافه بشه خوبه

**Comment by happybigboy** [comment]
همونجور که متین جان گفتن پیاده کردنش سخته . برای همین هست که مردم سوییچ کردن مرزبان و مرزنشین. یک ویژگی متمایز کننده باید باشه همیشه 😄
